//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.16 at 06:59:16 PM IST 
//


package com.scb.einvoice.seqnum;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.scb.einvoice.seqnum package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.scb.einvoice.seqnum
     * 
     */
    public ObjectFactory() {
        //
    }

    /**
     * Create an instance of {@link Country }
     * @return country
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link EInvoice }
     * @return einvoice
     * 
     */
    public EInvoice createEInvoice() {
        return new EInvoice();
    }

}
